name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.0.0
        with:
          path: .gradle
          key: gradle

      - name: Build
        run: ./gradlew clean assemble gh-pages -Pgpr.user=pmiklos -Pgpr.key=${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/gh-pages
